examensarbete/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'examensarbete.views.home', name='home'),
    # url(r'^examensarbete/', include('examensarbete.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('housingtrader.urls', namespace="housingtrader-index")),
    url(r'^login/', 'django.contrib.auth.views.login' , name='login'),
    url(r'^logout/', 'django.contrib.auth.views.logout' , name='logout'),
    url(r'^registration/', 'registration.views.register', name='register'),
    url(r'^/?', include('housingtrader.urls', namespace="housingtrader")),
)

housingtrader/urls.py
# -*- coding: utf-8 -*- 
'''
Created on 16 sep 2013

@author: Martin
'''
from django.conf.urls import patterns, url
from housingtrader import views

urlpatterns = patterns('',
    url(r'^$', views.search, name='search'),
    url(r'^dashboard/', views.index, name='index'),
    url(r'^create_listing/', views.create_listing, name='create_listing'),
    url(r'^(?P<listing_id>\d+)/change_published_state/', views.change_published_state, name='change_published_state'),
    url(r'^(?P<listing_id>\d+)/edit', views.edit_listing, name='edit_listing'),
    url(r'^(?P<pk>\d+)/delete', views.ListingDelete.as_view(), name='delete_listing'),
    url(r'^(?P<listing_id>\d+)/find_trades', views.find_trades, name='find_trades'),
    url(r'^(?P<listing_id>\d+)/(?P<other_listing_id>\d+)/detail', views.detail, name='detail'),
    url(r'^(?P<listing_id>\d+)/(?P<other_listing_id>\d+)/send_trade_request', views.send_trade_request, name='send_trade_request'),
    url(r'^(?P<requester_id>\d+)/(?P<receiver_id>\d+)/trade_request_detail', views.trade_request_detail, name='trade_request_detail'),
    url(r'^(?P<requester_id>\d+)/(?P<receiver_id>\d+)/trade_request_decline', views.trade_request_decline, name='trade_request_decline'),
    url(r'^(?P<listing_id>\d+)/preview', views.preview, name='preview'),
    url(r'^(?P<listing_id>\d+)/public_detail', views.public_detail, name='public_detail'),
)

housingtrader/models.py
# -*- coding: utf-8 -*- 
from django.db import models
from django.db.models.fields import CharField
from examensarbete.settings import AUTH_USER_MODEL
from localflavor.se.forms import COUNTY_CHOICES
import re

def generate_rooms_choices(max_rooms_choice):
    '''
    Creates the list of choices to use for rooms selection fields
    '''
    
    rooms_choices = list()
    
    for x in range(2, (max_rooms_choice + 1) * 2):
        if(x % 2 > 0):
            floated_x = float(x)
            choice = floated_x/2
        else:
            choice = x/2
        
        choice = str(choice)
        rooms_choices.append((x, choice))
        
    return rooms_choices

TYPE_TENANCY = 1
TYPE_BRF = 2
TYPE_HOUSE = 4

HOUSING_TYPE_CHOICES = (
    (TYPE_TENANCY, 'Hyresrätt'),
    (TYPE_BRF, 'Bostadsrätt'),
    (TYPE_HOUSE, 'Villa/Radhus')
)

def get_listing_fields_by_prefix(prefix):
    '''
    Get field names of the Listing model that have the provided prefix
    '''
    members = [attr for attr in dir(Listing()) if not callable(attr) and not attr.startswith("__")]
    fields = []
    for member in members:
        pattern = re.compile(prefix)
        if re.match(pattern, member):
            fields.append(member)
        
    return fields
    
    
BRF_NONE = 0
BRF_FORMED = 1
BRF_TO_BE = 2

BRF_STATUS_CHOICES = ((BRF_NONE, 'Ingen förening bildad'), (BRF_FORMED, 'Förening Bildad'), (BRF_TO_BE, 'Blivande Bostadsrätt'))
BRF_WANTED_STATUS_CHOICES = ((BRF_NONE, 'Nej'), (BRF_FORMED, 'Förening Bildad eller Blivande Bostadsrätt'), (BRF_TO_BE, 'Blivande Bostadsrätt'))
FLOOR_CHOICES = ((0, 'Inget krav'), (1, 'Ej nedre botten'))
    
MAX_ROOMS_CHOICE = 10
rooms_choices = generate_rooms_choices(MAX_ROOMS_CHOICE)

class Listing(models.Model):
    '''
    This model represents a listing for a housing trade
    It consists of data about the housing offered (o), and data about the housing wanted (w)
    '''
    
    creation_datetime = models.DateTimeField(auto_now_add=True)
    
    user = models.ForeignKey(AUTH_USER_MODEL)
    published = models.BooleanField(default=True)
    
    o_county = CharField(max_length=255, verbose_name='Län', choices=COUNTY_CHOICES)
    o_street_address = models.CharField(max_length=255, verbose_name='Gatuadress')
    o_postal_code = models.CharField(max_length=255, verbose_name='Postnummer')
    o_postal_town = models.CharField(max_length=255, verbose_name='Postort')
    o_rooms = models.PositiveIntegerField(choices=rooms_choices, verbose_name='Antal rum') # The number of rooms times 2, to avoid having to use floats or decimals
    o_area = models.PositiveIntegerField(verbose_name='Yta', help_text='kvm') # area in square meters
    o_type = models.PositiveIntegerField(choices=HOUSING_TYPE_CHOICES, verbose_name='Bostadstyp')
    o_rent = models.PositiveIntegerField(verbose_name = 'Hyra/Avgift', help_text='kr/mån')
    o_description = models.TextField(verbose_name='Beskrivning')
    o_brf_status = models.PositiveIntegerField(choices=BRF_STATUS_CHOICES, verbose_name='Om hyresrätt, är det blivande bostadsrätt?', null=True, blank=True)
    o_floor_no = models.IntegerField(verbose_name='Våning')
    o_has_fireplace = models.BooleanField(verbose_name='Öppen spis', default=False)
    o_has_balcony = models.BooleanField(verbose_name='Balkong', default=False)
    o_has_elevator = models.BooleanField(verbose_name='Hiss', default=False)
    
    w_county = CharField(max_length=255, verbose_name='Län', choices=COUNTY_CHOICES)
    w_min_rooms = models.PositiveIntegerField(choices=rooms_choices, verbose_name='Minsta antal rum')
    w_min_area = models.PositiveIntegerField(verbose_name='Minsta yta', help_text='kvm') # area in square meters
    w_max_rent = models.PositiveIntegerField(verbose_name='Max hyra', help_text='kr/mån')
    w_types = models.CommaSeparatedIntegerField(max_length=255, verbose_name='Önskade bostadstyper')
    w_brf_status = models.PositiveIntegerField(choices=BRF_WANTED_STATUS_CHOICES, verbose_name='Blivande bostadsrätt?', null=True, blank=True)
    w_has_fireplace = models.BooleanField(verbose_name='Öppen spis')
    w_has_balcony = models.BooleanField(verbose_name='Balkong')
    w_has_elevator = models.BooleanField(verbose_name='Hiss')
    w_not_bottom_floor = models.BooleanField(verbose_name='Våning', choices=FLOOR_CHOICES)
    
    def listing_search(self):
        '''
        Finds published listings where the offered parameters match this listing's wanted parameters
        '''
        
        wanted_types = str(self.w_types).split(',')
        
        matches = Listing.objects.filter(
            o_county = self.w_county,
            o_rooms__gte = self.w_min_rooms,
            o_area__gte = self.w_min_area,
            o_rent__lte = self.w_max_rent,
            o_type__in = wanted_types,
            published = True
        )
        
        if self.w_brf_status is not None:
            matches = matches.filter(
                o_brf_status__gte = self.w_brf_status
            )
            
        if self.w_has_fireplace:
            matches = matches.filter(o_has_fireplace = True)
            
        if self.w_has_elevator:
            matches = matches.filter(o_has_elevator = True)
            
        if self.w_has_balcony:
            matches = matches.filter(o_has_balcony = True)
            
        if self.w_not_bottom_floor:
            matches = matches.filter(o_floor_no__gt = 0)
        
        return matches
    
    def find_matches(self):
        '''
        Finds listings of other users where the offered parameters match this listing's wanted parameters
        '''
        
        return self.listing_search().exclude(user=self.user)
    
    def find_reverse_matches(self):
        '''
        Finds published listings of other users where the wanted parameters match this listing's offered parameters
        '''
        
        matches = Listing.objects.filter(
            w_county = self.o_county,
            w_min_rooms__lte = self.o_rooms,
            w_min_area__lte = self.o_area,
            w_max_rent__gte = self.o_rent,
            w_has_fireplace__lte = self.o_has_fireplace,
            w_has_elevator__lte = self.o_has_elevator,
            w_has_balcony__lte = self.w_has_balcony,
            published = True
        ).exclude(user = self.user)
        
        final_matches = []
        for listing in matches:
            if listing.w_not_bottom_floor and self.o_floor_no < 1:
                continue
            
            wanted_types = str(listing.w_types).split(',')
            
            if str(self.o_type) not in wanted_types:
                continue
            
            if listing.w_brf_status is not None and self.o_brf_status < listing.w_brf_status:
                continue
            
            final_matches.append(listing)
                
        return final_matches
    
    def find_mutual_matches(self):
        '''
        Finds listings where the offered and wanted parameters match each other
        '''
        
        matches= self.find_matches()
        reverse_matches = self.find_reverse_matches()
        
        return set(matches).intersection(reverse_matches)
    
    def change_published_state(self):
        self.published = not bool(self.published)
        self.save()
    
    def get_w_types_display(self):
        '''
        Returns a comma separated string of housing type values
        '''
        
        housing_types = dict(HOUSING_TYPE_CHOICES)
        wanted_type_ids = str(self.w_types).split(',')
        wanted_types_verbose = []
        for type_id in wanted_type_ids:
            type_id = type_id.strip()
            housingtype = housing_types[int(type_id)]
            wanted_types_verbose.append(housingtype)
            
        return ', '.join(wanted_types_verbose)
    
    def __unicode__(self):
        return self.o_street_address
    
    class Meta:
        verbose_name='Annons'
        verbose_name_plural='Annonser'
        
class TradeRequest(models.Model):
    creation_datetime = models.DateTimeField(auto_now_add=True)
    requester = models.ForeignKey(Listing, related_name='trade_requests_sent')
    receiver = models.ForeignKey(Listing, related_name='trade_requests_received')
    viewed_by_receiver = models.BooleanField(default=False)
    declined_by_receiver = models.BooleanField(default=False)
    
    def __unicode__(self):
        return str(self.requester) + ' bytes mot ' + str(self.receiver)
    
    class Meta:
        unique_together = ('requester', 'receiver')
    

housingtrader/forms.py
# -*- coding: utf-8 -*- 
from django.forms import Form, ModelForm, MultipleChoiceField, CharField, IntegerField, ChoiceField
from django.forms.widgets import CheckboxSelectMultiple
from housingtrader.models import Listing, HOUSING_TYPE_CHOICES, FLOOR_CHOICES, get_listing_fields_by_prefix
from localflavor.se.forms import SEPostalCodeField, SECountySelect

def get_wanted_fields():
    '''
    Wrapper function that gets the names of all fields in the Listing model that starts with w_,
    AKA the prefix of the 'wanted' fields.
    
    The function is used to exclude these fields in the 'offered' part of the form,
    and to include only these fields in the 'wanted' part of the form
    '''
    return get_listing_fields_by_prefix('w_')


'''
This is a Django snippet that provides a checkbox widget that works with a CommaSeparatedIntegerField,
which is exactly what we need for the 'Wanted housing types' field.
Source: http://djangosnippets.org/snippets/2860/
'''

# Widget
class CSICheckboxSelectMultiple(CheckboxSelectMultiple):
    def value_from_datadict(self, data, files, name):
        # Return a string of comma separated integers since the database, and
        # field expect a string (not a list).
        return ','.join(data.getlist(name))

    def render(self, name, value, attrs=None, choices=()):
        # Convert comma separated integer string to a list, since the checkbox
        # rendering code expects a list (not a string)
        if value:
            value = value.split(',')
        return super(CSICheckboxSelectMultiple, self).render(
            name, value, attrs=attrs, choices=choices
        )


# Form field
class CSIMultipleChoiceField(MultipleChoiceField):
    widget = CSICheckboxSelectMultiple

    # Value is stored and retrieved as a string of comma separated
    # integers. We don't want to do processing to convert the value to
    # a list like the normal MultipleChoiceField does.
    def to_python(self, value):
        return value

    def validate(self, value):
        # If we have a value, then we know it is a string of comma separated
        # integers. To use the MultipleChoiceField validator, we first have
        # to convert the value to a list.
        if value:
            value = value.split(',')
        super(CSIMultipleChoiceField, self).validate(value)


class ListingOfferedForm(ModelForm):
    '''
    The 'offered' part of the Listing form
    '''
    o_county = CharField(widget=SECountySelect, label='Län')
    o_postal_code = SEPostalCodeField(label='Postnummer')

    class Meta:
        '''
        User and published fields should also be excluded
        '''
        excluded_fields = get_wanted_fields()
        excluded_fields.append('user')
        excluded_fields.append('published')
        
        model = Listing
        exclude = excluded_fields

class ListingWantedForm(ModelForm):
    '''
    The 'wanted' part of the Listing form
    '''
    w_types = CSIMultipleChoiceField(required=True, choices=HOUSING_TYPE_CHOICES, label='Önskade bostadstyper')
    w_county = CharField(widget=SECountySelect, label='Län')
    
    class Meta:
        model = Listing
        fields = get_wanted_fields()
        
class CompleteListingForm(ModelForm):
    '''
    The complete Listing form
    ''' 
    w_types = CSIMultipleChoiceField(required=True, choices=HOUSING_TYPE_CHOICES, label='Önskade bostadstyper')
    
    def __init__(self, user=None, *args, **kwargs):
        '''
        @type user: User 
        '''
        super(CompleteListingForm, self).__init__(*args, **kwargs)
        
        self.user = user
    
    def save(self):
        listing = super(CompleteListingForm, self).save(commit=False)
        listing.user = self.user
        listing.save()
    
    class Meta:
        model = Listing
        exclude = ('user', 'published')
        
class SearchForm(Form):
    yes_or_none_choices = ((0, 'Inget krav'), (1, 'Ja'))
    
    text = CharField(label='Fritext', required=False)
    county = CharField(widget=SECountySelect, label='Län')
    types = CSIMultipleChoiceField(label='Bostadstyp(er)', choices=HOUSING_TYPE_CHOICES)
    min_area = IntegerField(label='Minsta yta (kvm)')
    min_rooms = IntegerField(label='Minsta antal rum')
    max_rent = IntegerField(label='Max hyra/avgift')
    has_fireplace = ChoiceField(label='Öppen spis', choices=yes_or_none_choices)
    has_balcony = ChoiceField(label='Balkong', choices=yes_or_none_choices)
    has_elevator = ChoiceField(label='Hiss', choices=yes_or_none_choices)
    not_bottom_floor = ChoiceField(label='Våning', choices=FLOOR_CHOICES)

housingtrader/templates/housingtrader/detail.html
{% extends "housingtrader/detailbase.html" %}
{% block functions %}
	{% if trade_request_exists %}
		<p>Du har redan gjort en intresseanmälan för det här bytet.</p>
	{% elif reverse_trade_request_exists %}
		<p>Den här annonsören har anmält intresse för din bostad. Gå <a href="{% url 'housingtrader:trade_request_detail' listing.id my_listing.id %}">hit</a> för att se bytet!</p>
	{% elif my_listing.user == listing.user %}
		<p>Detta är din egen bostadsannons.</p>
	{% else %}
		<form action="{% url 'housingtrader:send_trade_request' my_listing.id listing.id %}" method="post">
			{% csrf_token %}
			<input type="submit" value="Anmäl intresse för att byta {{ my_listing }} mot denna bostad" />
		</form>
		<p>När du gör en intresseanmälan får användaren tillgång till kontaktuppgifterna som du har angett.</p>
	{% endif %}
{% endblock %}

housingtrader/templates/housingtrader/detailbase.html
{% extends "housingtrader/housingtrader_base.html" %}

{% block page_header %}{{ listing }}{% endblock %}

{% block main %}

{% block functions %}{% endblock %}

<h2>Finnes</h2>
<ul class="offered">
	<li>Bostadstyp: {{ listing.get_o_type_display }}</li>
	<li>Adress: {{ listing.o_street_address }}</li>
	<li>Postnummer: {{ listing.o_postal_code }}</li>
	<li>Postort: {{ listing.o_postal_town }}</li>
	<li>Län: {{ listing.get_o_county_display }}</li>
	<li>Area: {{ listing.o_area}}</li>
	<li>Antal rum: {{ listing.get_o_rooms_display}}</li>
	<li>Hyra/Avgift: {{ listing.o_rent}}</li>
	<li>Våning: {{ listing.o_floor_no}}</li>
	<li>{{ listing.get_o_brf_status_display }}</li>
	<li>Öppen spis/Kakelugn: {{ listing.o_has_fireplace|yesno:"Ja,Nej" }}</li>
	<li>Balkong: {{ listing.o_has_balcony|yesno:"Ja,Nej" }}</li>
	<li>Hiss: {{ listing.o_has_elevator|yesno:"Ja,Nej" }}</li>
	<li class="description"><p>{{ listing.o_description }}</p></li>
</ul>
<h2>Sökes</h2>
<ul class="wanted">
	<li>Bostadstyp(er): {{ listing.get_w_types_display }} </li>
	<li>Län: {{ listing.get_w_county_display }}</li>
	<li>Minsta antal rum: {{ listing.get_w_min_rooms_display }}</li>
	<li>Minsta area: {{ listing.w_min_area }}</li>
	<li>Max hyra/avgift: {{ listing.w_max_rent }}</li>
	<li>Blivande bostadsrätt: {{ listing.get_w_brf_status_display }}</li>
	<li>Öppen spis/kakelugn: {{ listing.w_has_fireplace|yesno:"Ja,Inget krav" }}</li>
	<li>Balkong: {{ listing.w_has_balcony|yesno:"Ja,Inget krav" }}</li>
	<li>Hiss: {{ listing.w_has_elevator|yesno:"Ja,Inget krav" }}</li>
	<li>Våning: {{ listing.get_w_not_bottom_floor_display }}</li>
</ul>
{% endblock %}

housingtrader/templates/housingtrader/find_trades.html
{% extends "housingtrader/housingtrader_base.html" %}

{% block page_header %}Byten för {{ my_listing }}{% endblock %}

{% block main %}

{% if basic_matches %}
	<h2>Bostäder som matchar dina önskemål:</h2>
	<table>
		<thead>
			<tr>
				<td>Adress</td>
				<td>Postnummer</td>
				<td>Postort</td>
				<td>Län</td>
				<td>Area (kvm)</td>
				<td>Hyra/Avgift (kr/mån)</td>
			</tr>
		</thead>
		<tbody>
		{% for other_listing in basic_matches %}
			<tr>
				<td><a href="{% url 'housingtrader:detail' my_listing.id other_listing.id %}">{{ other_listing }}</a></td>
				<td>{{ other_listing.o_postal_code }}</td>
				<td>{{ other_listing.o_postal_town }}</td>
				<td>{{ other_listing.get_o_county_display }}</td>
				<td>{{ other_listing.o_area }}</td>
				<td>{{ other_listing.o_rent }}</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
{% endif %}

{% if reverse_matches %}
	<h2>Annonser med önskemål som matchar din bostad:</h2>
	<table>
		<thead>
			<tr>
				<td>Adress</td>
				<td>Postnummer</td>
				<td>Postort</td>
				<td>Län</td>
				<td>Area (kvm)</td>
				<td>Hyra/Avgift (kr/mån)</td>
			</tr>
		</thead>
		<tbody>
		{% for other_listing in reverse_matches %}
			<tr>
				<td><a href="{% url 'housingtrader:detail' my_listing.id other_listing.id %}">{{ other_listing }}</a></td>
				<td>{{ other_listing.o_postal_code }}</td>
				<td>{{ other_listing.o_postal_town }}</td>
				<td>{{ other_listing.get_o_county_display }}</td>
				<td>{{ other_listing.o_area }}</td>
				<td>{{ other_listing.o_rent }}</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
{% endif %}

{% endblock %}

housingtrader/templates/housingtrader/housingtrader_base.html
{% extends "base.html" %}

{% load staticfiles %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'housingtrader/css/main.css' %}">
{% endblock %}

housingtrader/templates/housingtrader/index.html
{% extends "housingtrader/housingtrader_base.html" %}

{% load staticfiles %}

{% block page_header %}Välkommen {{ user.first_name }}!{% endblock %}

{% block main %}

{% if listings %}
	<h2>Dina annonser:</h2>
	<table>
		<thead>
			<tr>
				<td>Annons</td>
				<td>Redigera</td>
				<td>Hitta byten</td>
				<td>Ändra status</td>
				<td>Ta bort</td>
			</tr>
		</thead>
		<tbody>
		{% for listing in listings %}
			<tr>
				<td><a href="{% url 'housingtrader:preview' listing.id %}">{{ listing }}</td>
				<td>
					<a href="{% url 'housingtrader:edit_listing' listing.id %}">
						<img src="{% static 'housingtrader/img/edit.png' %}"
					</a>
				</td>
				<td>
					<a href="{% url 'housingtrader:find_trades' listing.id %}">
						<img src="{% static 'housingtrader/img/search.png' %}"
					</a>
				</td>
				<td>
					<form action="{% url 'housingtrader:change_published_state' listing.id %}" method='post'>
						{% csrf_token %}
						<input type="submit" value="{{ listing.published|yesno:'Avpublicera,Publicera'}}" />
					</form>
				</td>
				<td>
					<form action="{% url 'housingtrader:delete_listing' listing.id %}" method='get'>
						<input type="submit" value="x" />
					</form>
				</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
	<p><a href="{% url 'housingtrader:create_listing' %}">Skapa en ny annons</a></p>
{% else %}
	<p>Du har inga annonser. <a href="{% url 'housingtrader:create_listing' %}">Skapa en annons här!</a></p>
{% endif %}

{% if trade_requests%}
	<h2>Mottagna bytesförfrågningar:</h2>
	<ul>
	{% for trade_request in trade_requests %}
		<li>
			<a href="{% url 'housingtrader:trade_request_detail' trade_request.requester.id trade_request.receiver.id %}"><strong>{{ trade_request.requester.o_street_address }}</strong>
			bytes mot <strong>{{ trade_request.receiver.o_street_address }}</strong></a>
		</li>
	{% endfor %}
	</ul>
{% endif %}

{% endblock %}

housingtrader/templates/housingtrader/listing_confirm_delete.html
{% extends "housingtrader/housingtrader_base.html" %}

{% block page_header %}Är du säker på att du vill ta bort annonsen för {{ listing }}?{% endblock %}

{% block main %}
<form action="{% url 'housingtrader:delete_listing' listing.pk %}" method="post">
	{% csrf_token %}
	<input type="submit" value="Ja, ta bort den!" />
</form>
<p><a href="{% url 'housingtrader:index' %}">Nej, jag har ångrat mig!</a></p>
{% endblock %}

housingtrader/templates/housingtrader/search_results.html
{% extends "housingtrader/housingtrader_base.html" %}

{% block page_header %} Välkommen till Housingtrader {% endblock %}

{% block main %}
<h2>Sök bland bostadsannonser:</h2>
{% include "housingtrader/search_form.html" %}

{% if results %}
	<h2>Hittade Annonser:</h2>
	<table>
		<thead>
			<tr>
				<td>Adress</td>
				<td>Postnummer</td>
				<td>Postort</td>
				<td>Län</td>
				<td>Area (kvm)</td>
				<td>Hyra/Avgift (kr/mån)</td>
			</tr>
		</thead>
		<tbody>
		{% for listing in results %}
			<tr>
				<td><a href="{% url 'housingtrader:public_detail' listing.id %}">{{ listing }}</a></td>
				<td>{{ listing.o_postal_code }}</td>
				<td>{{ listing.o_postal_town }}</td>
				<td>{{ listing.get_o_county_display }}</td>
				<td>{{ listing.o_area }}</td>
				<td>{{ listing.o_rent }}</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>Hittade inga annonser</p>
{% endif %}
{% endblock %}

housingtrader/templates/housingtrader/trade_request_detail.html
{% extends "housingtrader/housingtrader_base.html" %}

{% block page_header %}Mottaget Bytesförslag{% endblock %}

{% block main %}
<h2>Användaren {{ requester.user.get_full_name }} vill byta följande bostad:</h2>
<ul class="requester">
	<li>Bostadstyp: {{ requester.get_o_type_display }}</li>
	<li>Adress: {{ requester.o_street_address }}</li>
	<li>Postnummer: {{ requester.o_postal_code }}</li>
	<li>Postort: {{ requester.o_postal_town }}</li>
	<li>Län: {{ requester.get_o_county_display }}</li>
	<li>Area: {{ requester.o_area }}</li>
	<li>Antal rum: {{ requester.get_o_rooms_display}}</li>
	<li>Hyra/Avgift: {{ requester.o_rent }}</li>
	<li>Våning: {{ requester.o_floor_no }}</li>
	<li>Blivande bostadsrätt: {{ requester.get_o_brf_status_display }}</li>
	<li>Öppen spis/Kakelugn: {{ requester.o_has_fireplace|yesno:"Ja,Nej" }}</li>
	<li>Balkong: {{ requester.o_has_balcony|yesno:"Ja,Nej" }}</li>
	<li>Hiss: {{ requester.o_has_elevator|yesno:"Ja,Nej" }}</li>
	<li class="description"><p>{{ requester.o_description }}</p></li>
</ul>
<h2>Mot din bostad:</h2>
<ul class="receiver">
    <li>Bostadstyp: {{ receiver.get_o_type_display }}</li>
    <li>Adress: {{ receiver.o_street_address }}</li>
    <li>Postnummer: {{ receiver.o_postal_code }}</li>
    <li>Postort: {{ receiver.o_postal_town }}</li>
    <li>Län: {{ receiver.get_o_county_display }}</li>
    <li>Area: {{ receiver.o_area }}</li>
    <li>Antal rum: {{ receiver.get_o_rooms_display }}</li>
    <li>Hyra/Avgift: {{ receiver.o_rent }}</li>
    <li>Våning: {{ receiver.o_floor_no }}</li>
    <li>Blivande bostadsrätt: {{ receiver.get_o_brf_status_display }}</li>
    <li>Öppen spis/Kakelugn: {{ receiver.o_has_fireplace|yesno:"Ja,Nej" }}</li>
    <li>Balkong: {{ receiver.o_has_balcony|yesno:"Ja,Nej" }}</li>
    <li>Hiss: {{ receiver.o_has_elevator|yesno:"Ja,Nej" }}</li>
    <li class="description"><p>{{ receiver.o_description }}</p></li>
</ul>

<h2>Användarens kontaktuppgifter</h2>
<ul class="contactinfo">
    <li>E-post: {{ requester.user.email }}</li>
    <li>Telefonnummer: {{ requester.user.phone_number }}</li>
</ul>
{% if trade_request.declined_by_receiver %}
    <p>Du har tackat nej till det här bytesförslaget, men du kan fortfarande kontakta användaren om du har ångrat dig.</p>
{% else %}
    <form action="{% url 'housingtrader:trade_request_decline' requester.id receiver.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Tacka nej till bytet" />
    </form>
{% endif %}
{% endblock %}