examensarbete/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'examensarbete.views.home', name='home'),
    # url(r'^examensarbete/', include('examensarbete.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('housingtrader.urls', namespace="housingtrader-index")),
    url(r'^login/', 'django.contrib.auth.views.login' , name='login'),
    url(r'^logout/', 'django.contrib.auth.views.logout' , name='logout'),
    url(r'^registration/', 'registration.views.register', name='register'),
    url(r'^/?', include('housingtrader.urls', namespace="housingtrader")),
)

housingtrader/urls.py
# -*- coding: utf-8 -*- 
'''
Created on 16 sep 2013

@author: Martin
'''
from django.conf.urls import patterns, url
from housingtrader import views

urlpatterns = patterns('',
    url(r'^$', views.search, name='search'),
    url(r'^dashboard/', views.index, name='index'),
    url(r'^create_listing/', views.create_listing, name='create_listing'),
    url(r'^(?P<listing_id>\d+)/change_published_state/', views.change_published_state, name='change_published_state'),
    url(r'^(?P<listing_id>\d+)/edit', views.edit_listing, name='edit_listing'),
    url(r'^(?P<pk>\d+)/delete', views.ListingDelete.as_view(), name='delete_listing'),
    url(r'^(?P<listing_id>\d+)/find_trades', views.find_trades, name='find_trades'),
    url(r'^(?P<listing_id>\d+)/(?P<other_listing_id>\d+)/detail', views.detail, name='detail'),
    url(r'^(?P<listing_id>\d+)/(?P<other_listing_id>\d+)/send_trade_request', views.send_trade_request, name='send_trade_request'),
    url(r'^(?P<requester_id>\d+)/(?P<receiver_id>\d+)/trade_request_detail', views.trade_request_detail, name='trade_request_detail'),
    url(r'^(?P<requester_id>\d+)/(?P<receiver_id>\d+)/trade_request_decline', views.trade_request_decline, name='trade_request_decline'),
    url(r'^(?P<listing_id>\d+)/preview', views.preview, name='preview'),
    url(r'^(?P<listing_id>\d+)/public_detail', views.public_detail, name='public_detail'),
)

examensarbete/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>{% block title %}Housingtrader{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	{% block extra_css %}{% endblock %}
	<meta charset="UTF-8" />
</head>
<body>
    <div id="mainwrapper">
        <h1>{% block page_header %}{% endblock %}</h1>
        
        <ul class="user_functions">
            <li><a href="{% url 'housingtrader:search' %}">Startsidan</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'housingtrader:index' %}">Dashboard</a></li>
            <li><a href="{% url 'logout' %}">Logga ut</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Logga in</a></li>
            <li><a href="{% url 'register' %}">Registrera konto</a></li>
            {% endif %}
        </ul>
        
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        
        {% block main %}
        {% endblock %}
    </div>
</body>
</html>